elasticsearch:
  host_url: wp-p2m-30.ebi.ac.uk:9200,wp-p2m-31.ebi.ac.uk:9200,wp-p2m-32.ebi.ac.uk:9200
management.health.elasticsearch.enabled: false
server:
  port: 9050
  servlet.contextPath: "/pride/multiomics/ws"
logging.level:
  org.elasticsearch: TRACE
  org.springframework.data.elasticsearch: TRACE
  org.springframework.data.elasticsearch.client.WIRE : TRACE
  org.springframework.data.elasticsearch.core: DEBUG
spring.mvc.async.request-timeout: -1
springdoc:
  api-docs:
    enabled: true
    path: '/api-docs'
  swagger-ui:
    tagsSorter: alpha
    disable-swagger-default-url: true