spring.application.name: $app_name

logging:
  file.path: $logspath/logs_${HOSTNAME}/

elasticsearch.host_url: $elasticsearch_hosts

management.health.elasticsearch.enabled: false

server:
  port: $port
  servlet.contextPath: $contextPath

spring.mvc.async.request-timeout: -1

springdoc:
  api-docs:
    enabled: true
    path: '/api-docs'
  swagger-ui:
    tagsSorter: alpha
    disable-swagger-default-url: true